version: '3.9'

networks:
  net:
  db:

services:
  # Flask Microservice
  cars:
    networks:
      net:
        aliases:
          - cars
    build: cars/
    container_name: cars
    command: flask run
    volumes: 
      - ./cars/app:/app

  # Flask Microservice
  books:
    networks:
      net:
        aliases:
          - books
    build: books/
    container_name: books
    command: flask run
    volumes: 
      - ./books/app:/app

  # PHP Microservice
  articles:
    networks:
      net:
        aliases:
          - articles
    build: articles/
    container_name: articles
    volumes:
      - ./articles/app:/var/www/html

  # Gateway PostgreSQL
  gateway_db:
    networks:
      db:
        aliases: 
          - postgres
    image: postgres:12
    environment: 
      - POSTGRES_DB=gateway_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: gateway_db

  # Gateway PGAdmin
  gateway_pga:
    networks:
      - db
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=maciej.nachtygal@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on: 
      - gateway_db

  # Flask Gateway
  gateway:
    networks:
      - net
      - db
    build: api-gateway/
    command: flask run
    ports: 
      - "5000:5000"
    volumes: 
      - ./api-gateway/app:/app
    depends_on: 
      - gateway_db